### ISSUE TITLE
Az stopped working with GF 2.3

### ISSUE THREAD

**Issue by rafaehlers** [gravityview/GravityView-AZ-Filters#25]
![gv-final-parameters](https://user-images.githubusercontent.com/1222472/38889303-aea65732-4254-11e8-90d0-8ddc6324faf8.jpg)

**Comment by rafaehlers** [comment]
https://secure.helpscout.net/conversation/563191522/14182/

**Comment by rafaehlers** [comment]
https://secure.helpscout.net/conversation/563388519/14186

**Comment by soulseekah** [comment]
There's the A-Z 2.0 rewrite branch for 2.0 that has been tested, if anyone is on 2.0-beta they could try that. I'll look regarding just GF 2.3. Thanks.

**Comment by soulseekah** [comment]
This was fixed in https://github.com/gravityview/GravityView-AZ-Filters/commit/418f03de4fadabdb483d990331082186dfc90c9b and merged into both `2.0` and `develop` branches. Just needs a release @zackkatz 

In fact now that 2.3 is released (finally!!!!) all develop branches have to be produced as updates, I fixed all our plugins for 2.3 compatibility back in November!
